"""uuid update

Revision ID: 22a4bfb9d189
Revises: 
Create Date: 2025-05-25 12:05:57.221210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a4bfb9d189'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admini',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('heslo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admini_email'), 'admini', ['email'], unique=True)
    op.create_table('mechanici',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('heslo', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nazev', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazev')
    )
    op.create_table('zakaznici',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('heslo', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('adresa', sa.String(), nullable=True),
    sa.Column('anonymizovan', sa.Boolean(), nullable=True),
    sa.Column('smazano', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mechanik_role',
    sa.Column('mechanik_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mechanik_id'], ['mechanici.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('zakazky',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('popis', sa.String(), nullable=False),
    sa.Column('stav', sa.String(), nullable=True),
    sa.Column('hotova', sa.Boolean(), nullable=True),
    sa.Column('datum_prijmu', sa.Date(), nullable=True),
    sa.Column('datum_predani', sa.Date(), nullable=True),
    sa.Column('auto_znacka', sa.String(), nullable=True),
    sa.Column('auto_model', sa.String(), nullable=True),
    sa.Column('auto_vin', sa.String(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('anonymizovana', sa.Boolean(), nullable=True),
    sa.Column('smazano', sa.Boolean(), nullable=True),
    sa.Column('zakaznik_id', sa.UUID(), nullable=True),
    sa.Column('mechanik_id', sa.UUID(), nullable=True),
    sa.Column('vytvoril_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mechanik_id'], ['mechanici.id'], ),
    sa.ForeignKeyConstraint(['vytvoril_id'], ['admini.id'], ),
    sa.ForeignKeyConstraint(['zakaznik_id'], ['zakaznici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logy_zakazek',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zakazka_id', sa.UUID(), nullable=True),
    sa.Column('provedl_id', sa.UUID(), nullable=True),
    sa.Column('akce', sa.String(), nullable=True),
    sa.Column('popis', sa.Text(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zakazka_id'], ['zakazky.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logy_zakazek')
    op.drop_table('zakazky')
    op.drop_table('mechanik_role')
    op.drop_table('zakaznici')
    op.drop_table('role')
    op.drop_table('mechanici')
    op.drop_index(op.f('ix_admini_email'), table_name='admini')
    op.drop_table('admini')
    # ### end Alembic commands ###
