"""vytvoreni tabulek

Revision ID: 7e1f62de9261
Revises: 
Create Date: 2025-05-21 07:04:36.762917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1f62de9261'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('heslo', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_mechanici_id'), 'mechanici', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazev')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('zakaznici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('heslo', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('adresa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_zakaznici_id'), 'zakaznici', ['id'], unique=False)
    op.create_table('mechanik_role',
    sa.Column('mechanik_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanik_id'], ['mechanici.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('zakazky',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('popis', sa.String(), nullable=False),
    sa.Column('stav', sa.String(), nullable=True),
    sa.Column('datum_prijmu', sa.Date(), nullable=True),
    sa.Column('datum_predani', sa.Date(), nullable=True),
    sa.Column('auto_znacka', sa.String(), nullable=True),
    sa.Column('auto_model', sa.String(), nullable=True),
    sa.Column('auto_vin', sa.String(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('zakaznik_id', sa.Integer(), nullable=True),
    sa.Column('mechanik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanik_id'], ['mechanici.id'], ),
    sa.ForeignKeyConstraint(['zakaznik_id'], ['zakaznici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakazky_id'), 'zakazky', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zakazky_id'), table_name='zakazky')
    op.drop_table('zakazky')
    op.drop_table('mechanik_role')
    op.drop_index(op.f('ix_zakaznici_id'), table_name='zakaznici')
    op.drop_table('zakaznici')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_mechanici_id'), table_name='mechanici')
    op.drop_table('mechanici')
    # ### end Alembic commands ###
